substitutions:
  devicename: sonoff-4ch-pro
  human_devicename: Sonoff 4CH Pro

esphome:
  name: $devicename

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
# Encryption highly recommended - see https://esphome.io/components/api.html
#   encryption:
#     key: 

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${human_devicename} Button 1"
    on_press:
      - switch.toggle: relay_1
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${human_devicename} Button 2"
    on_press:
      - switch.toggle: relay_2
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${human_devicename} Button 3"
    on_press:
      - switch.toggle: relay_3
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${human_devicename} Button 4"
    on_press:
      - switch.toggle: relay_4
  - platform: status
    name: "${human_devicename} Status"

text_sensor:
  - platform: version
    name: ${human_devicename} ESPHome Version
    disabled_by_default: true

sensor:
  - platform: wifi_signal
    name: ${human_devicename} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${human_devicename} Uptime
    id: uptime_sensor
    update_interval: 60s

switch:
  - platform: gpio
    name: "${human_devicename} Relay 1"
    pin: GPIO12
    id: relay_1
  - platform: gpio
    name: "${human_devicename} Relay 2"
    pin: GPIO5
    id: relay_2
  - platform: gpio
    name: "${human_devicename} Relay 3"
    pin: GPIO4
    id: relay_3
  - platform: gpio
    name: "${human_devicename} Relay 4"
    pin: GPIO15
    id: relay_4

# Use the blue LED as the Status indicator
# https://esphome.io/components/light/status_led.html
light:
  - platform: status_led
    name: "${human_devicename} Blue LED"
    pin: GPIO13
